configuration: Release
version: 0.1.{build}
nuget:
  account_feed: true
  project_feed: true
  
init:
  - git config --global core.autocrlf true
  
before_build:
- ps: >-
    invoke-webrequest https://go.microsoft.com/fwlink/?LinkID=827524 -OutFile core.exe
    core.exe /install /quiet /norestart
    dotnet restore

artifacts:
 - path: artifacts\bin\TurboLinks.Net\Release\*.nupkg