configuration: Release
version: 0.1.{build}
nuget:
  account_feed: true
  
init:
  - git config --global core.autocrlf true
  
before_build:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm upgrade
 - ps: dnvm update-self
 - ps: dnvm install 1.0.0-beta8
 - ps: dnvm list
 - ps: dnvm use 1.0.0-beta8
 - ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

artifacts:
 - path: artifacts\bin\TurboLinks.Net\Release\*.nupkg